package win

//ref CRYPT_ATTRIBUTE_TYPE_VALUE
//ref CRYPT_ALGORITHM_IDENTIFIER
//ref CRYPT_HASH_BLOB

type SIP_INDIRECT_DATA struct {
	Data            CRYPT_ATTRIBUTE_TYPE_VALUE
	DigestAlgorithm CRYPT_ALGORITHM_IDENTIFIER
	Digest          CRYPT_HASH_BLOB
}
