package win

//ref USER_MARSHAL_SIZING_ROUTINE
//ref USER_MARSHAL_MARSHALLING_ROUTINE
//ref USER_MARSHAL_UNMARSHALLING_ROUTINE
//ref USER_MARSHAL_FREEING_ROUTINE
type USER_MARSHAL_ROUTINE_QUADRUPLE struct {
	PfnBufferSize uintptr // USER_MARSHAL_SIZING_ROUTINE
	PfnMarshall   uintptr // USER_MARSHAL_MARSHALLING_ROUTINE
	PfnUnmarshall uintptr // USER_MARSHAL_UNMARSHALLING_ROUTINE
	PfnFree       uintptr // USER_MARSHAL_FREEING_ROUTINE
}
