package win

//ref UINT
//ref HWND
//ref HINSTANCE
//ref TASKDIALOG_FLAGS
//ref TASKDIALOG_COMMON_BUTTON_FLAGS
//ref PCWSTR
//ref HICON
//ref LONG_PTR
//ref TASKDIALOG_BUTTON
//ref TASKDIALOGCALLBACK
