package win

//ref GENERIC_UNBIND_ROUTINE
//ref GENERIC_BINDING_ROUTINE
type GENERIC_BINDING_ROUTINE_PAIR struct {
	PfnBind   uintptr // GENERIC_BINDING_ROUTINE
	PfnUnbind uintptr // GENERIC_UNBIND_ROUTINE
}
